{{- range .Values.clusters }}
{{- if .apps.sampleApp.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{printf "%s-%s" .name "nginx"}}
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: {{ .namespace }}
    server: {{ .destinationServer }}
  project: {{ .project }}
  source:
    path: nginx-chart
    repoURL: 'https://github.com/jielingit/argocd-demo.git'
    targetRevision: {{ .apps.sampleApp.branch }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
{{- end }}
---

{{- end }}
